# Generated by Django 2.2.12 on 2021-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('ticket_id', models.IntegerField(unique=True)),
                ('seat_no', models.IntegerField(default=0)),
            ],
        ),
    ]
